version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo npm install -g surge
      - run: surge --project ./public --domain public-tree-map.surge.sh
